// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210409105721_AddPackagesTable")]
    partial class AddPackagesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataLayer.Models.Package", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("DataLayer.Models.Speed", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PackageID")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PackageID");

                    b.ToTable("Speeds");
                });

            modelBuilder.Entity("DataLayer.Models.Time", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PackageID")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("PackageID");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("DataLayer.Models.Speed", b =>
                {
                    b.HasOne("DataLayer.Models.Package", null)
                        .WithMany("Speeds")
                        .HasForeignKey("PackageID");
                });

            modelBuilder.Entity("DataLayer.Models.Time", b =>
                {
                    b.HasOne("DataLayer.Models.Package", null)
                        .WithMany("Times")
                        .HasForeignKey("PackageID");
                });
#pragma warning restore 612, 618
        }
    }
}
